name: TEST

on:
  push:
    paths-ignore:
      - "build/**"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v2
      - name: docker build
        run: make docker-rebuild
      - name: build check
        run: |
          rm -f build/*.out
          make rebuild ARG="--user root"
          if [[ -z $(find build -name "fileEncSys.out" -type f) ]]; then
            ls -l build
            exit 1
          fi

  test-build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v2
      - name: docker build
        run: |
          cd test
          pwd
          ls -l
          make docker-rebuild
      - name: build
        run: |
          cd test
          make rebuild ARG="--user root"
      - name: run
        run: |
          cd test
          ls -l
          make run
