name: TEST

on:
  push:
    paths-ignore:
      - "build/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        cd test
        make clean
        make
    - name: run
      run: |
        cd test
        make run